# Site settings
title: M-i78 / 10#
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: baozi
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://m-i78.github.io" # the base hostname & protocol for your site
